parameters:
#    news_admin.example.class: News\AdminBundle\Example

services:
#    news_admin.example:
#        class: %news_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
